package content

import (
	"deutsch-tui/internal/core"
)

func A2WorkOfficeDeck() core.Deck {
	notes := []core.Note{
		{ID: "a2-wo-beruf", DeckID: "a2-work-office", Front: "der Beruf", Back: "job/profession", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-karriere", DeckID: "a2-work-office", Front: "die Karriere", Back: "career", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-erfahrung", DeckID: "a2-work-office", Front: "die Erfahrung", Back: "experience", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-faehigkeit", DeckID: "a2-work-office", Front: "die Fähigkeit", Back: "skill/ability", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-qualifikation", DeckID: "a2-work-office", Front: "die Qualifikation", Back: "qualification", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-ausbildung", DeckID: "a2-work-office", Front: "die Ausbildung", Back: "apprenticeship/training", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-weiterbildung", DeckID: "a2-work-office", Front: "die Weiterbildung", Back: "continuing education", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-schulung", DeckID: "a2-work-office", Front: "die Schulung", Back: "training", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-bewerbung", DeckID: "a2-work-office", Front: "die Bewerbung", Back: "application", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-lebenslauf", DeckID: "a2-work-office", Front: "der Lebenslauf", Back: "CV/resume", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-anschreiben", DeckID: "a2-work-office", Front: "das Anschreiben", Back: "cover letter", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-vorstellungsgespraech", DeckID: "a2-work-office", Front: "das Vorstellungsgespräch", Back: "interview", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-einstellung", DeckID: "a2-work-office", Front: "die Einstellung", Back: "hiring", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-probezeit", DeckID: "a2-work-office", Front: "die Probezeit", Back: "probation period", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kuendigung", DeckID: "a2-work-office", Front: "die Kündigung", Back: "termination", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kuendigungsfrist", DeckID: "a2-work-office", Front: "die Kündigungsfrist", Back: "notice period", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-abfindung", DeckID: "a2-work-office", Front: "die Abfindung", Back: "severance pay", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-arbeitszeugnis", DeckID: "a2-work-office", Front: "das Arbeitszeugnis", Back: "employment reference", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-arbeitszeit", DeckID: "a2-work-office", Front: "die Arbeitszeit", Back: "working hours", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-gleitzeit", DeckID: "a2-work-office", Front: "die Gleitzeit", Back: "flexible hours", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-schichtarbeit", DeckID: "a2-work-office", Front: "die Schichtarbeit", Back: "shift work", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-nachtschicht", DeckID: "a2-work-office", Front: "die Nachtschicht", Back: "night shift", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-teilzeit", DeckID: "a2-work-office", Front: "die Teilzeit", Back: "part-time", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-vollzeit", DeckID: "a2-work-office", Front: "die Vollzeit", Back: "full-time", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-gehalt", DeckID: "a2-work-office", Front: "das Gehalt", Back: "salary", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-lohn", DeckID: "a2-work-office", Front: "der Lohn", Back: "wage", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-praemie", DeckID: "a2-work-office", Front: "die Prämie", Back: "bonus", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-ueberstunde", DeckID: "a2-work-office", Front: "die Überstunde", Back: "overtime", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-pause", DeckID: "a2-work-office", Front: "die Pause", Back: "break", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-mittagspause", DeckID: "a2-work-office", Front: "die Mittagspause", Back: "lunch break", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-teepause", DeckID: "a2-work-office", Front: "die Teepause", Back: "coffee break", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-versicherung", DeckID: "a2-work-office", Front: "die Versicherung", Back: "insurance", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-krankenversicherung", DeckID: "a2-work-office", Front: "die Krankenversicherung", Back: "health insurance", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-rentenversicherung", DeckID: "a2-work-office", Front: "die Rentenversicherung", Back: "pension insurance", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-arbeitslosenversicherung", DeckID: "a2-work-office", Front: "die Arbeitslosenversicherung", Back: "unemployment insurance", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-pflegeversicherung", DeckID: "a2-work-office", Front: "die Pflegeversicherung", Back: "long-term care insurance", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-steuer", DeckID: "a2-work-office", Front: "die Steuer", Back: "tax", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-abgabe", DeckID: "a2-work-office", Front: "die Abgabe", Back: "fee/levy", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-sozialabgaben", DeckID: "a2-work-office", Front: "die Sozialabgaben", Back: "social security contributions", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-aufgabe", DeckID: "a2-work-office", Front: "die Aufgabe", Back: "task/assignment", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-verantwortung", DeckID: "a2-work-office", Front: "die Verantwortung", Back: "responsibility", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-deadline", DeckID: "a2-work-office", Front: "die Deadline", Back: "deadline", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-prioritaet", DeckID: "a2-work-office", Front: "die Priorität", Back: "priority", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-dringlichkeit", DeckID: "a2-work-office", Front: "die Dringlichkeit", Back: "urgency", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-besprechung", DeckID: "a2-work-office", Front: "die Besprechung", Back: "meeting", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-konferenz", DeckID: "a2-work-office", Front: "die Konferenz", Back: "conference", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-praesentation", DeckID: "a2-work-office", Front: "die Präsentation", Back: "presentation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-vortrag", DeckID: "a2-work-office", Front: "der Vortrag", Back: "talk/lecture", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-diskussion", DeckID: "a2-work-office", Front: "die Diskussion", Back: "discussion", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-entscheidung", DeckID: "a2-work-office", Front: "die Entscheidung", Back: "decision", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-vereinbarung", DeckID: "a2-work-office", Front: "die Vereinbarung", Back: "agreement", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-bestuetigung", DeckID: "a2-work-office", Front: "die Bestätigung", Back: "confirmation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-rueckmeldung", DeckID: "a2-work-office", Front: "die Rückmeldung", Back: "feedback", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kritik", DeckID: "a2-work-office", Front: "die Kritik", Back: "criticism", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-lob", DeckID: "a2-work-office", Front: "das Lob", Back: "praise", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-befoerderung", DeckID: "a2-work-office", Front: "die Beförderung", Back: "promotion", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-abteilung", DeckID: "a2-work-office", Front: "die Abteilung", Back: "department", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-team", DeckID: "a2-work-office", Front: "das Team", Back: "team", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-zusammenarbeit", DeckID: "a2-work-office", Front: "die Zusammenarbeit", Back: "cooperation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kommunikation", DeckID: "a2-work-office", Front: "die Kommunikation", Back: "communication", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-email", DeckID: "a2-work-office", Front: "die E-Mail", Back: "email", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-nachricht", DeckID: "a2-work-office", Front: "die Nachricht", Back: "message", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-telefonat", DeckID: "a2-work-office", Front: "das Telefonat", Back: "phone call", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-anruf", DeckID: "a2-work-office", Front: "der Anruf", Back: "phone call", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-rueckruf", DeckID: "a2-work-office", Front: "der Rückruf", Back: "callback", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-durchwahl", DeckID: "a2-work-office", Front: "die Durchwahl", Back: "extension number", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-projekt", DeckID: "a2-work-office", Front: "das Projekt", Back: "project", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-ergebnis", DeckID: "a2-work-office", Front: "das Ergebnis", Back: "result", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-loesung", DeckID: "a2-work-office", Front: "die Lösung", Back: "solution", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-problem", DeckID: "a2-work-office", Front: "das Problem", Back: "problem", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-verbesserung", DeckID: "a2-work-office", Front: "die Verbesserung", Back: "improvement", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-aenderung", DeckID: "a2-work-office", Front: "die Änderung", Back: "change", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-fortschritt", DeckID: "a2-work-office", Front: "der Fortschritt", Back: "progress", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-planung", DeckID: "a2-work-office", Front: "die Planung", Back: "planning", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-ziel", DeckID: "a2-work-office", Front: "das Ziel", Back: "goal/target", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-strategie", DeckID: "a2-work-office", Front: "die Strategie", Back: "strategy", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-motivation", DeckID: "a2-work-office", Front: "die Motivation", Back: "motivation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-leistung", DeckID: "a2-work-office", Front: "die Leistung", Back: "performance/achievement", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-belohnung", DeckID: "a2-work-office", Front: "die Belohnung", Back: "reward", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-erinnerung", DeckID: "a2-work-office", Front: "die Erinnerung", Back: "reminder", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-einladung", DeckID: "a2-work-office", Front: "die Einladung", Back: "invitation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-teilnahme", DeckID: "a2-work-office", Front: "die Teilnahme", Back: "participation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-absage", DeckID: "a2-work-office", Front: "die Absage", Back: "cancellation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-zusage", DeckID: "a2-work-office", Front: "die Zusage", Back: "acceptance", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-entschuldigung", DeckID: "a2-work-office", Front: "die Entschuldigung", Back: "apology", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-begruessung", DeckID: "a2-work-office", Front: "die Begrüßung", Back: "greeting", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-verabschiedung", DeckID: "a2-work-office", Front: "die Verabschiedung", Back: "farewell", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-frage", DeckID: "a2-work-office", Front: "die Frage", Back: "question", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-antwort", DeckID: "a2-work-office", Front: "die Antwort", Back: "answer", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-information", DeckID: "a2-work-office", Front: "die Information", Back: "information", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-erklaerung", DeckID: "a2-work-office", Front: "die Erklärung", Back: "explanation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-anweisung", DeckID: "a2-work-office", Front: "die Anweisung", Back: "instruction", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-regel", DeckID: "a2-work-office", Front: "die Regel", Back: "rule", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-vorschrift", DeckID: "a2-work-office", Front: "die Vorschrift", Back: "regulation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-richtlinie", DeckID: "a2-work-office", Front: "die Richtlinie", Back: "guideline", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-politik", DeckID: "a2-work-office", Front: "die Politik", Back: "policy", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kultur", DeckID: "a2-work-office", Front: "die Kultur", Back: "culture (workplace)", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-atmosphaere", DeckID: "a2-work-office", Front: "die Atmosphäre", Back: "atmosphere", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-wartezeit", DeckID: "a2-work-office", Front: "die Wartezeit", Back: "waiting time", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-betriebsrat", DeckID: "a2-work-office", Front: "der Betriebsrat", Back: "works council", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-gewerkschaft", DeckID: "a2-work-office", Front: "die Gewerkschaft", Back: "trade union", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-arbeitnehmer", DeckID: "a2-work-office", Front: "der Arbeitnehmer", Back: "employee", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-arbeitgeber", DeckID: "a2-work-office", Front: "der Arbeitgeber", Back: "employer", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-selbstaendige", DeckID: "a2-work-office", Front: "der Selbstständige", Back: "self-employed person", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-freiberufler", DeckID: "a2-work-office", Front: "der Freiberufler", Back: "freelancer", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-gruender", DeckID: "a2-work-office", Front: "der Gründer", Back: "founder", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-unternehmer", DeckID: "a2-work-office", Front: "der Unternehmer", Back: "entrepreneur", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-geschaeftsfuehrer", DeckID: "a2-work-office", Front: "der Geschäftsführer", Back: "managing director", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-geschaeftspartner", DeckID: "a2-work-office", Front: "der Geschäftspartner", Back: "business partner", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-lieferant", DeckID: "a2-work-office", Front: "der Lieferant", Back: "supplier", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kunde", DeckID: "a2-work-office", Front: "der Kunde", Back: "customer", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kundin", DeckID: "a2-work-office", Front: "die Kundin", Back: "customer (female)", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-klient", DeckID: "a2-work-office", Front: "der Klient", Back: "client", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-mandant", DeckID: "a2-work-office", Front: "der Mandant", Back: "client (legal)", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-nutzer", DeckID: "a2-work-office", Front: "der Nutzer", Back: "user", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-konsument", DeckID: "a2-work-office", Front: "der Konsument", Back: "consumer", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-zielgruppe", DeckID: "a2-work-office", Front: "die Zielgruppe", Back: "target group", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-marke", DeckID: "a2-work-office", Front: "die Marke", Back: "brand", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-nachfrage", DeckID: "a2-work-office", Front: "die Nachfrage", Back: "demand", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-angebot", DeckID: "a2-work-office", Front: "das Angebot", Back: "supply", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-konkurrenz", DeckID: "a2-work-office", Front: "die Konkurrenz", Back: "competition", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-preis", DeckID: "a2-work-office", Front: "der Preis", Back: "price", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kosten", DeckID: "a2-work-office", Front: "die Kosten", Back: "costs", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-rabatt", DeckID: "a2-work-office", Front: "der Rabatt", Back: "discount", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-verhandlung", DeckID: "a2-work-office", Front: "die Verhandlung", Back: "negotiation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-unterschrift", DeckID: "a2-work-office", Front: "die Unterschrift", Back: "signature", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-genehmigung", DeckID: "a2-work-office", Front: "die Genehmigung", Back: "approval", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-quittung", DeckID: "a2-work-office", Front: "die Quittung", Back: "receipt", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-rechnung", DeckID: "a2-work-office", Front: "die Rechnung", Back: "invoice", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-zahlung", DeckID: "a2-work-office", Front: "die Zahlung", Back: "payment", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kreditkarte", DeckID: "a2-work-office", Front: "die Kreditkarte", Back: "credit card", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-bankueberweisung", DeckID: "a2-work-office", Front: "die Banküberweisung", Back: "bank transfer", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-barzahlung", DeckID: "a2-work-office", Front: "die Barzahlung", Back: "cash payment", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-ratenzahlung", DeckID: "a2-work-office", Front: "die Ratenzahlung", Back: "installment payment", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kaution", DeckID: "a2-work-office", Front: "die Kaution", Back: "deposit", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-miete", DeckID: "a2-work-office", Front: "die Miete", Back: "rent", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-nebenkosten", DeckID: "a2-work-office", Front: "die Nebenkosten", Back: "utility costs", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-buchhaltung", DeckID: "a2-work-office", Front: "die Buchhaltung", Back: "accounting", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-bilanz", DeckID: "a2-work-office", Front: "die Bilanz", Back: "balance sheet", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-gewinn", DeckID: "a2-work-office", Front: "der Gewinn", Back: "profit", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-verlust", DeckID: "a2-work-office", Front: "der Verlust", Back: "loss", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-umsatz", DeckID: "a2-work-office", Front: "der Umsatz", Back: "revenue", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-investition", DeckID: "a2-work-office", Front: "die Investition", Back: "investment", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-ruecklage", DeckID: "a2-work-office", Front: "die Rücklage", Back: "reserve", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-dividende", DeckID: "a2-work-office", Front: "die Dividende", Back: "dividend", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-aktie", DeckID: "a2-work-office", Front: "die Aktie", Back: "share/stock", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-boerse", DeckID: "a2-work-office", Front: "die Börse", Back: "stock exchange", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-wirtschaft", DeckID: "a2-work-office", Front: "die Wirtschaft", Back: "economy", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-branche", DeckID: "a2-work-office", Front: "die Branche", Back: "industry/sector", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-firma", DeckID: "a2-work-office", Front: "die Firma", Back: "company", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-gmbh", DeckID: "a2-work-office", Front: "die GmbH", Back: "LLC", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-ag", DeckID: "a2-work-office", Front: "die AG", Back: "public limited company", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-einzelunternehmen", DeckID: "a2-work-office", Front: "das Einzelunternehmen", Back: "solo business", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-partnerschaft", DeckID: "a2-work-office", Front: "die Partnerschaft", Back: "partnership", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kooperation", DeckID: "a2-work-office", Front: "die Kooperation", Back: "cooperation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-fusion", DeckID: "a2-work-office", Front: "die Fusion", Back: "merger", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-uebernahme", DeckID: "a2-work-office", Front: "die Übernahme", Back: "acquisition", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-gruendung", DeckID: "a2-work-office", Front: "die Gründung", Back: "foundation/startup", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-insolvenz", DeckID: "a2-work-office", Front: "die Insolvenz", Back: "insolvency/bankruptcy", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-sanierung", DeckID: "a2-work-office", Front: "die Sanierung", Back: "restructuring", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-wachstum", DeckID: "a2-work-office", Front: "das Wachstum", Back: "growth", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-expansion", DeckID: "a2-work-office", Front: "die Expansion", Back: "expansion", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-innovation", DeckID: "a2-work-office", Front: "die Innovation", Back: "innovation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kreativitaet", DeckID: "a2-work-office", Front: "die Kreativität", Back: "creativity", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-flexibilitaet", DeckID: "a2-work-office", Front: "die Flexibilität", Back: "flexibility", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-effizienz", DeckID: "a2-work-office", Front: "die Effizienz", Back: "efficiency", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-produktivitaet", DeckID: "a2-work-office", Front: "die Produktivität", Back: "productivity", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-qualitaet", DeckID: "a2-work-office", Front: "die Qualität", Back: "quality", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kundenzufriedenheit", DeckID: "a2-work-office", Front: "die Kundenzufriedenheit", Back: "customer satisfaction", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-kampagne", DeckID: "a2-work-office", Front: "die Kampagne", Back: "campaign", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-werbung", DeckID: "a2-work-office", Front: "die Werbung", Back: "advertising", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-helpdesk", DeckID: "a2-work-office", Front: "der Helpdesk", Back: "help desk", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-hotline", DeckID: "a2-work-office", Front: "die Hotline", Back: "hotline", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-faq", DeckID: "a2-work-office", Front: "die FAQ", Back: "FAQ", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-dokumentation", DeckID: "a2-work-office", Front: "die Dokumentation", Back: "documentation", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-fehlerbehebung", DeckID: "a2-work-office", Front: "die Fehlerbehebung", Back: "troubleshooting", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-fehlermeldung", DeckID: "a2-work-office", Front: "die Fehlermeldung", Back: "Error message", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-konfiguration", DeckID: "a2-work-office", Front: "die Konfiguration", Back: "configuration", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-einstellung-setting", DeckID: "a2-work-office", Front: "die Einstellung", Back: "setting", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-datenbank", DeckID: "a2-work-office", Front: "die Datenbank", Back: "database", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-api", DeckID: "a2-work-office", Front: "die API", Back: "API", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-sicherheit", DeckID: "a2-work-office", Front: "die Sicherheit", Back: "security/safety", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-verschluesselung", DeckID: "a2-work-office", Front: "die Verschlüsselung", Back: "encryption", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-firewall", DeckID: "a2-work-office", Front: "die Firewall", Back: "firewall", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-backup", DeckID: "a2-work-office", Front: "das Backup", Back: "backup", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-wiederherstellung", DeckID: "a2-work-office", Front: "die Wiederherstellung", Back: "recovery", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-risiko", DeckID: "a2-work-office", Front: "das Risiko", Back: "risk", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-auswirkung", DeckID: "a2-work-office", Front: "die Auswirkung", Back: "impact", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-bewertung", DeckID: "a2-work-office", Front: "die Bewertung", Back: "evaluation/assessment", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-korrekturmassnahme", DeckID: "a2-work-office", Front: "die Korrekturmaßnahme", Back: "corrective action", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-praeventivmassnahme", DeckID: "a2-work-office", Front: "die Präventivmaßnahme", Back: "preventive measure", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-wartung", DeckID: "a2-work-office", Front: "die Wartung", Back: "maintenance", Tags: []string{"a2", "work"}},
		{ID: "a2-wo-reparatur", DeckID: "a2-work-office", Front: "die Reparatur", Back: "repair", Tags: []string{"a2", "work"}},
	}

	for i := range notes {
		notes[i].Cards = CardsForNote(notes[i])
	}

	return core.Deck{
		ID:          "a2-work-office",
		Name:        "A2 Work & Office",
		Description: "Intermediate vocabulary for workplace, office, business, and professional life in German.",
		Tags:        []string{"german", "a2", "work", "office", "business"},
		Notes:       notes,
	}
}
