package content

type ConjunctionExercise struct {
	Sentence    string
	Answer      string
	Meaning     string
	Hint        string
	Explanation string
}

func GetConjunctionExercises() []ConjunctionExercise {
	return []ConjunctionExercise{
		{
			Sentence:    "Ich bleibe heute zu Hause, {{...}} es regnet.",
			Answer:      "weil",
			Meaning:     "because",
			Hint:        "Subordinating (verb to end)",
			Explanation: "weil (because) is a subordinating conjunction: it sends the verb (regnet) to the end of the clause.",
		},
		{
			Sentence:    "Er lernt Deutsch, {{...}} er in Deutschland leben möchte.",
			Answer:      "weil",
			Meaning:     "because",
			Hint:        "Subordinating (verb to end)",
			Explanation: "weil (because) is a subordinating conjunction: it sends the verb (möchte) to the end of the clause.",
		},
		{
			Sentence:    "Es regnet, {{...}} ich gehe trotzdem spazieren.",
			Answer:      "aber",
			Meaning:     "but",
			Hint:        "Coordinating (ADUSO, position 0)",
			Explanation: "aber (but) is a coordinating conjunction (ADUSO): it occupies position 0 and does not change the word order (verb 'gehe' is in position 2).",
		},
		{
			Sentence:    "Ich gehe ins Bett, {{...}} ich bin sehr müde.",
			Answer:      "denn",
			Meaning:     "because",
			Hint:        "Coordinating (ADUSO, position 0)",
			Explanation: "denn (because/for) is a coordinating conjunction (ADUSO): it occupies position 0 and does not change the word order (verb 'bin' is in position 2).",
		},
		{
			Sentence:    "Es ist kalt, {{...}} ziehe ich einen Mantel an.",
			Answer:      "deshalb",
			Meaning:     "therefore",
			Hint:        "Conjunctive Adverb (inversion)",
			Explanation: "deshalb (therefore) is a conjunctive adverb: it triggers inversion (verb 'ziehe' comes immediately after it).",
		},
		{
			Sentence:    "Sie weiß nicht, {{...}} er morgen kommt.",
			Answer:      "ob",
			Meaning:     "if/whether",
			Hint:        "Subordinating (verb to end)",
			Explanation: "ob (whether) is a subordinating conjunction: it sends the verb (kommt) to the end of the clause.",
		},
		{
			Sentence:    "Ich rufe dich an, {{...}} ich am Bahnhof ankomme.",
			Answer:      "wenn",
			Meaning:     "when/if",
			Hint:        "Subordinating (verb to end)",
			Explanation: "wenn (when/if) is a subordinating conjunction: it sends the verb (ankomme) to the end of the clause.",
		},
		{
			Sentence:    "Er hat viel gelernt, {{...}} hat er die Prüfung nicht bestanden.",
			Answer:      "trotzdem",
			Meaning:     "nevertheless",
			Hint:        "Conjunctive Adverb (inversion)",
			Explanation: "trotzdem (nevertheless) is a conjunctive adverb: it triggers inversion (verb 'hat' comes immediately after it).",
		},
		{
			Sentence:    "Wir essen Pizza {{...}} wir gehen ins Restaurant.",
			Answer:      "oder",
			Meaning:     "or",
			Hint:        "Coordinating (ADUSO, position 0)",
			Explanation: "oder (or) is a coordinating conjunction (ADUSO): it occupies position 0 and does not change the word order.",
		},
		{
			Sentence:    "Ich hoffe, {{...}} du dich bald besser fühlst.",
			Answer:      "dass",
			Meaning:     "that",
			Hint:        "Subordinating (verb to end)",
			Explanation: "dass (that) is a subordinating conjunction: it sends the verb (fühlst) to the end of the clause.",
		},
		{
			Sentence:    "Sie geht zum Deutschkurs, {{...}} sie möchte schneller lernen.",
			Answer:      "denn",
			Meaning:     "because",
			Hint:        "Coordinating (ADUSO, position 0)",
			Explanation: "denn (because/for) is a coordinating conjunction (ADUSO): it does not change the word order (verb 'möchte' remains in position 2).",
		},
		{
			Sentence:    "Er hat kein Auto, {{...}} fährt er mit dem Fahrrad.",
			Answer:      "deshalb",
			Meaning:     "therefore",
			Hint:        "Conjunctive Adverb (inversion)",
			Explanation: "deshalb (therefore) is a conjunctive adverb: it triggers inversion (verb 'fährt' immediately follows it).",
		},
		{
			Sentence:    "Wir bleiben drinnen, {{...}} der Sturm vorbei ist.",
			Answer:      "bis",
			Meaning:     "until",
			Hint:        "Subordinating (verb to end)",
			Explanation: "bis (until) is a subordinating conjunction: it sends the verb (ist) to the end of the clause.",
		},
		{
			Sentence:    "Ich trinke keinen Kaffee, {{...}} lieber Tee.",
			Answer:      "sondern",
			Meaning:     "but rather",
			Hint:        "Coordinating (ADUSO, position 0)",
			Explanation: "sondern (but rather) is a coordinating conjunction (ADUSO): it introduces a correction and does not change the word order.",
		},
		{
			Sentence:    "Obwohl es schneit, {{...}} die Kinder draußen.",
			Answer:      "spielen",
			Meaning:     "are playing",
			Hint:        "Main clause verb position",
			Explanation: "Since 'obwohl' is a subordinating conjunction starting the sentence, the entire subordinating clause occupies position 1, forcing the main clause verb (spielen) to position 2 (immediately after the comma).",
		},
		{
			Sentence:    "Ich weiß, {{...}} er heute nicht kommt.",
			Answer:      "dass",
			Meaning:     "that",
			Hint:        "Subordinating (verb to end)",
			Explanation: "dass (that) is a subordinating conjunction: it sends the verb (kommt) to the end of the clause.",
		},
		{
			Sentence:    "Wir gehen spazieren, {{...}} es regnet.",
			Answer:      "obwohl",
			Meaning:     "although",
			Hint:        "Subordinating (verb to end)",
			Explanation: "obwohl (although) is a subordinating conjunction: it sends the verb (regnet) to the end of the clause.",
		},
		{
			Sentence:    "Er ist müde, {{...}} er arbeitet weiter.",
			Answer:      "aber",
			Meaning:     "but",
			Hint:        "Coordinating (ADUSO, position 0)",
			Explanation: "aber (but) is a coordinating conjunction (ADUSO): it does not change the word order.",
		},
		{
			Sentence:    "Ich komme mit, {{...}} ich Zeit habe.",
			Answer:      "falls",
			Meaning:     "in case / if",
			Hint:        "Subordinating (verb to end)",
			Explanation: "falls (in case) is a subordinating conjunction: it sends the verb (habe) to the end of the clause.",
		},
		{
			Sentence:    "Zuerst essen wir, {{...}} gehen wir ins Kino.",
			Answer:      "dann",
			Meaning:     "then",
			Hint:        "Conjunctive Adverb (inversion)",
			Explanation: "dann (then) is a conjunctive adverb: it triggers inversion, so the verb (gehen) comes immediately after it.",
		},
		{
			Sentence:    "Sie lernt viel, {{...}} sie will die Prüfung bestehen.",
			Answer:      "denn",
			Meaning:     "because",
			Hint:        "Coordinating (ADUSO, position 0)",
			Explanation: "denn (because) is a coordinating conjunction: it occupies position 0 and doesn't change the verb position.",
		},
		{
			Sentence:    "Er hat Hunger, {{...}} isst er einen Apfel.",
			Answer:      "darum",
			Meaning:     "therefore / for that reason",
			Hint:        "Conjunctive Adverb (inversion)",
			Explanation: "darum (therefore) is a conjunctive adverb: it triggers inversion, verb (isst) in position 2.",
		},
		{
			Sentence:    "Ich frage mich, {{...}} er das gemacht hat.",
			Answer:      "warum",
			Meaning:     "why",
			Hint:        "Indirect Question (verb to end)",
			Explanation: "warum (why) in an indirect question acts like a subordinating conjunction: verb (hat) to the end.",
		},
		{
			Sentence:    "Wir warten hier, {{...}} der Bus kommt.",
			Answer:      "bis",
			Meaning:     "until",
			Hint:        "Subordinating (verb to end)",
			Explanation: "bis (until) is a subordinating conjunction: verb (kommt) to the end.",
		},
		{
			Sentence:    "Entweder wir gehen jetzt, {{...}} wir bleiben hier.",
			Answer:      "oder",
			Meaning:     "or",
			Hint:        "Coordinating (ADUSO, position 0)",
			Explanation: "oder (or) is a coordinating conjunction (ADUSO): it does not change the word order.",
		},
		{
			Sentence:    "Seitdem er in Berlin wohnt, {{...}} er viel Deutsch.",
			Answer:      "spricht",
			Meaning:     "speaks",
			Hint:        "Main clause verb position",
			Explanation: "When the 'seitdem' subordinating clause comes first, the main clause verb (spricht) must be in position 2 (immediately after the comma).",
		},
		{
			Sentence:    "Ich trinke Tee, {{...}} ich bin erkältet.",
			Answer:      "denn",
			Meaning:     "because",
			Hint:        "Coordinating (ADUSO, position 0)",
			Explanation: "denn (because) is a coordinating conjunction (ADUSO): position 0, verb 'bin' stays in position 2.",
		},
		{
			Sentence:    "Es ist schon spät, {{...}} müssen wir gehen.",
			Answer:      "daher",
			Meaning:     "therefore",
			Hint:        "Conjunctive Adverb (inversion)",
			Explanation: "daher (therefore) is a conjunctive adverb: it triggers inversion, verb 'müssen' in position 2.",
		},
		{
			Sentence:    "Bevor wir essen, {{...}} wir uns die Hände.",
			Answer:      "waschen",
			Meaning:     "wash",
			Hint:        "Main clause verb position",
			Explanation: "When the 'bevor' subordinating clause comes first, the main clause verb (waschen) follows the comma (position 2).",
		},
		{
			Sentence:    "Er ist nicht nur klug, {{...}} auch sehr nett.",
			Answer:      "sondern",
			Meaning:     "but (rather)",
			Hint:        "Multi-part conjunction",
			Explanation: "sondern (but rather) is part of a multi-part conjunction 'nicht nur... sondern auch'.",
		},
		{
			Sentence:    "Ich bleibe zu Hause, {{...}} ich krank bin.",
			Answer:      "da",
			Meaning:     "since / because",
			Hint:        "Subordinating (verb to end)",
			Explanation: "da (since) is a subordinating conjunction: it sends the verb (bin) to the end of the clause.",
		},
		{
			Sentence:    "Während ich koche, {{...}} sie Musik.",
			Answer:      "hört",
			Meaning:     "listens to",
			Hint:        "Main clause verb position",
			Explanation: "When the 'während' subordinating clause starts the sentence, the main clause verb (hört) follows the comma.",
		},
		{
			Sentence:    "Er kommt heute nicht, {{...}} er ist beschäftigt.",
			Answer:      "denn",
			Meaning:     "because",
			Hint:        "Coordinating (ADUSO, position 0)",
			Explanation: "denn (because) is a coordinating conjunction: it does not change the word order.",
		},
		{
			Sentence:    "Wir haben kein Geld, {{...}} können wir nicht in den Urlaub fahren.",
			Answer:      "trotzdem",
			Meaning:     "nevertheless",
			Hint:        "Conjunctive Adverb (inversion)",
			Explanation: "trotzdem (nevertheless) is a conjunctive adverb: it triggers inversion, verb 'können' in position 2.",
		},
		{
			Sentence:    "Nachdem er gegessen hatte, {{...}} er schlafen.",
			Answer:      "ging",
			Meaning:     "went",
			Hint:        "Main clause verb position",
			Explanation: "After a 'nachdem' subordinating clause, the main clause verb (ging) must follow the comma.",
		},
	}
}
